apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kilian
  name: kilian
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kilian
  strategy: {}
  template:
    metadata:
      labels:
        app: kilian
    spec:
      containers:
      - image: replace
        name: kilian-container
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kilian
  name: kilian-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kilian
  type: NodePort